FROM python:3.11-slim

# Install libraries
COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /app
COPY scripts/ /app/scripts/
COPY .gc/ /app/.gc/

# Main script
CMD ["python", "/app/scripts/run_ml_ai.py"]
