main:
    params: [input]
    steps:
    - step1:
        call: googleapis.cloudbuild.v1.projects.builds.create
        args:
            projectId: fintech-intelligence-platform
            body:
                build:
                    steps:
                    - name: gcr.io/cloud-builders/gcloud
                      args:
                      - run
                      - jobs
                      - execute
                      - dbt-job
                      - --region=us-central1
                      - --project=fintech-intelligence-platform
                    - name: gcr.io/cloud-builders/gcloud
                      args:
                      - run
                      - jobs
                      - execute
                      - python-job
                      - --region=us-central1
                      - --project=fintech-intelligence-platform
                    timeout: 3600s
        result: build_result
